# Generated by Django 5.0.1 on 2024-01-20 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("men", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="men",
            name="author",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="men",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="men.category",
            ),
        ),
        migrations.AddField(
            model_name="men",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="men.tagpost"
            ),
        ),
        migrations.AddField(
            model_name="men",
            name="wife",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="husband",
                to="men.wife",
            ),
        ),
        migrations.AddIndex(
            model_name="men",
            index=models.Index(
                fields=["-time_created"], name="men_men_time_cr_ad832d_idx"
            ),
        ),
    ]
