# Generated by Django 5.0.1 on 2024-01-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("men", "0002_alter_men_options_men_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="men",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
