# Generated by Django 5.0.1 on 2024-01-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("men", "0003_alter_men_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="men",
            name="is_published",
            field=models.BooleanField(
                choices=[(0, "draft"), (1, "published")], default=0
            ),
        ),
    ]
