# Generated by Django 5.0.1 on 2024-01-13 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("men", "0007_tagpost_alter_men_cat_men_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wife",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name="men",
            name="wife",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="husband",
                to="men.wife",
            ),
        ),
    ]
