# Generated by Django 5.0.1 on 2024-01-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("men", "0008_wife_men_wife"),
    ]

    operations = [
        migrations.AddField(
            model_name="wife",
            name="m_count",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
