# Generated by Django 5.0.1 on 2024-01-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("men", "0009_wife_m_count"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads_model")),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="men",
            options={
                "ordering": ["-time_created"],
                "verbose_name": "Famous men",
                "verbose_name_plural": "Famous men",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="name_of_category"
            ),
        ),
        migrations.AlterField(
            model_name="men",
            name="title",
            field=models.CharField(max_length=255, verbose_name="My_title"),
        ),
    ]
