# Generated by Django 5.0.1 on 2024-01-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("men", "0010_uploadfiles_alter_category_options_alter_men_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="men",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="photos/%Y/%m/%d",
                verbose_name="Photo",
            ),
        ),
    ]
